version: '3.7'
services:
  echogram:
    image: ghcr.io/remiallain/echogram:latest
    env_file: .env
    environment:
      PYTHONUNBUFFERED: 1
      LOG_LEVEL: info
      EG_DATA_DIR: /app/data
      EG_SESSION_ID: ${SESSION_ID}
    volumes:
      - ./${SESSION_ID}.session:/app/${SESSION_ID}.session
      - ./data:/app/data