version: '3.7'
services:
  echogram:
    image: ghcr.io/remiallain/echogram:latest
    environment:
      PYTHONUNBUFFERED: 1
      LOG_LEVEL: info
      EG_DATA_DIR: /app/data
      EG_SESSION_ID: /app/sessions/anon
      EG_API_ID: 
      EG_API_HASH: 
      EG_CHANNELS: channel1,channel2,channel3
      EG_AUTO_JOIN_CHANNELS: 1
    volumes:
      - ./sessions:/app/sessions
      - ./data:/app/data